<?php

########################################################################
# Extension Manager/Repository config file for ext: "nbomn"
#
# Auto generated by Extension Builder 2011-06-16
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'MtoN',
	'description' => 'Example on how to create m:n Relations with Extbase and Fluid. This extension does nothing in the Frontend! Add a Folder in the Backend and insert new Category Objects',
	'category' => '',
	'author' => 'Noël Bossart',
	'author_email' => 'n.company@me.com',
	'author_company' => 'www.noelboss.ch',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'test',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>